// All player-visible strings (§11.3) — adding a language is a data change.
export const STR = {
  title: "Drops Adventure",
  tagline: "Wander the isle. Snack the gummies. Chase the light.",
  choose: "Choose your adventurer",
  howtoMove: "WASD — move",
  howtoLook: "Mouse — look",
  howtoSprint: "Shift — sprint (burns gummy power faster)",
  howtoJump: "Space — hop (tap twice to double jump)",
  howtoMoveTouch: "Left stick — move",
  howtoLookTouch: "Drag anywhere — look",
  howtoSprintTouch: "⚡ — sprint (burns gummy power faster)",
  howtoJumpTouch: "⤴ — hop (tap twice to double jump)",
  howtoGoal: "Walk into wiggling gummies to refill your power. By day you boogie — by night the sky goes wild.",
  clickToPlay: "Pick a hero to begin",
  energy: "GUMMY POWER",
  score: "Gummies",
  time: "Time",
  day: "Day",
  night: "Night",
  gameOver: "Sugar crash…",
  finalScore: "Gummies munched",
  finalTime: "You adventured for",
  best: "Best",
  restartHint: "R — play again · C — switch hero",
  restartHintTouch: "Tap Play Again · tap 🎭 to switch hero",
  playAgain: "PLAY AGAIN",
  runOver: "Adventure complete!",
  leaped: "Off the edge of the world!",
  callShip: "Signal for a ship",
  boardShip: "Climb aboard",
  travelTo: "Setting course for",
  resume: "RESUME",
  menuHint: "☰ — pause · 🏁 — stop & save score · 🎭 / C — switch hero (keeps your run) · M — mute",
  menuHintTouch: "☰ — pause · 🏁 — stop & save score · 🎭 — switch hero (keeps your run) · 🔊 — mute",
  switchTitle: "Switch hero",
  switchHint: "Your run keeps going — pick who finishes it",
  flavorsTitle: "Gummy Flavors",
  flavorsTag: "All 11 Drops flavors spawn on the island",
  close: "CLOSE",
  lbTitle: "Island Legends",
  lbEnter: "You made the leaderboard! Enter your initials:",
  lbSave: "SAVE",
  lbEmpty: "No legends yet — be the first!",
  topMunchers: "Top Munchers",
  topMunchersTag: "Here's the board so far",
  endGame: "END GAME",
  paused: "Paused — click to resume",
  seconds: "s",
  chars: {
    rave:      { name: "Kiki",    sub: "Rave Girl",     desc: "Pink boa. Big beats. Bigger boogie." },
    mountain:  { name: "Gus",     sub: "Mountain Man",  desc: "Beard, backpack, and a folk stomp." },
    goat:      { name: "Barnaby", sub: "Billy Goat",    desc: "Horns, a wine cask, zero chill." },
    budtender: { name: "Reggie",  sub: "The Budtender", desc: "Big hair, black leather, permanent haze." },
  },
};
